### PR TITLE
deadlinks out/replaced; DBAD and WTFPL in; Typo

### PR DESCRIPTION
**Pull request by encarsia**

### CODE REVIEW

**Comment by benlk** [comment]
Rather than removing the deadlink licenses, can you check for and link to archived versions of those licenses, if possible?

**Comment by encarsia** [comment]
Done.

**Review by benlk — APPROVED** [review]

**Comment by benlk** [comment]
You're cool with dual-licensing of these changes under CC-BY-SA 4.0 and https://github.com/benlk/misc-licenses/blob/master/schrodinger-license.md, specifically as regards the historical note?

**Comment by encarsia** [comment]
Sure (not sure whether I completely comprehend as I am not of feline origin (that's still a yes)).

**Pull request merged**
